### ISSUE TITLE
Visual block transpose

### ISSUE THREAD

**Issue by mvrozanti** [salsifis/vim-transpose#5]
Calling `:Transpose` [with a visual block produces unexpected output](https://asciinema.org/a/heRJ1HcPNqmUK0agr7ctUMimH).

Shouldn't the transformed text be as following?
```
agmdef
bhijkl
cnopqr
```

**Comment by salsifis** [comment]
vim-transpose works with lines of text, not blocks. This is the general philosophy of vim commands (`:g`, `:s`, `:r`).

What is implied in this issue is that you could transpose data in-place when it has the form of a square, and not work on lines.

This could be doable, but:
* it needs error handling because validation must be done on the squareness of the data;
* it is not trivial; measuring squareness is not always simple with Unicode for example;
* it would not be available as a :command, but rather as a mapping in visual mode, for `:` in visual mode expands automatically to `:'<,'>`, which means that the intent is to operate on lines.

I am willing to accept pull requests if someone can manage to write such a routine, but I think your best option is:
* `y`
* CTRL-W, n
* `:0put | $d _` (these first three instructions copy your visual block in a separate buffer
* `:Transpose`
* `G$`, CTRL-V, `goyZZgvp` (this sequence block-selects result, copies it, closes the temporary buffer, reselect last visual selection, and paste over).

You may map some shortcut to this sequence if needed.

**Comment by mvrozanti** [comment]
damn

well

ok
